version: '3'
services:
  database:
    image: postgres:15
    container_name: stock_db
    restart: always
    ports:
      - 5432:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./setup-master:/docker-entrypoint-initdb.d
    environment:
      - 'POSTGRES_PASSWORD=a_passwd234'
      - 'POSTGRES_DB=stock_service'
