version: '3'
services:
  database:
    image: postgres:15
    container_name: asi_psql
    restart: always
    ports:
      - "5432:5432"  # Permite conexões de qualquer lugar
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./setup-master:/docker-entrypoint-initdb.d
    environment:
      - 'POSTGRES_PASSWORD=a_passwd234'
      - 'POSTGRES_DB=asi_sales'
