version: '3'
services:
  lojaA:
    image: postgres:15
    container_name: asi_lojaA
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: asi_lojaA
      POSTGRES_DB: lojaAdb
    volumes:
      - ./data_lojaA:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./setup-masterlojaAdb:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  lojaB:
    image: postgres:15
    container_name: asi_lojaB
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: asi_lojaB
      POSTGRES_DB: lojaBdb
    volumes:
      - ./data_lojaB:/var/lib/postgresql/data
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./setup-masterlojaBdb:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  headquarters:
    image: postgres:15
    container_name: asi_headquarters
    restart: always
    depends_on:
      lojaA:
        condition: service_healthy
      lojaB:
        condition: service_healthy
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: asi_headquarters
      POSTGRES_DB: headquartersdb
    volumes:
      - ./data_headquarters:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./my-postgres.conf:/etc/postgresql/postgresql.conf
      - ./setup-masterheadquarters:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
